### ISSUE TITLE
Socket ID is not a reliable identifier

### ISSUE THREAD

**Issue by d-asensio** [t-mullen/simple-signal#12]
This package uses `socket.id` to identify the peers and forward requests from the initiator to the target. This would be fine if the `socket.id` would not mutate during the whole "life" of the peer, but sadly this is not the case.

Quoting [Socket.io documentation](https://socket.io/docs/server-api/#socket-id), they describe `socket.id` as:

> A unique identifier **for the session**, that comes from the underlying Client.

Meaning that the id could change if the session ends, for example (there are other reasons why the session could change: reconnection, transport change, etc.).

As a result, every time the server restarts, mappings between peers are lost and **simple-signaling-client** relaunches the discover event through the new socket session (with a new id):

https://github.com/t-mullen/simple-signal/blob/67132051ddded372c38f2566b0a56ad2c7d4f822/client/src/simple-signal-client.js#L24-L26

In this case the server is not aware of this new id's and the other connected **simple-signaling-client**s neither, this causes the `ready` event to be fired again for peers that were already connected.

Since it's difficult to explain this issue, I have prepared a gif using the example code of this repo to show it better:

![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/13970905/46964427-51c8d700-d0a8-11e8-9e47-63466e3c4b88.gif)

You can find the source code [here](https://github.com/d-asensio/simple-signal-socket-id-failure)

### Possible solutions:

I have been thinking on how to solve this issue, and a possible solution could be adding a condition to avoid firing the ready event if the id has change:

Turning this:
https://github.com/t-mullen/simple-signal/blob/67132051ddded372c38f2566b0a56ad2c7d4f822/client/src/simple-signal-client.js#L36-L41

Into this:

```javascript
SimpleSignalClient.prototype._onDiscover = function (data) { 
   var self = this 
  
   if (self.id === null || self.id === data.id) {
      self.emit('ready', data.metadata)
   }
   self.id = data.id
 } 
```

I will submit a PR once I test it properly (I think that other adjustments are required to make it work).

Another possible solution could be generating `self.id` on the client via `cuid()` and stop relying on `socket.id`, this would be ideal because then we can attach to the `connect` event just once and avoid to broadcast redundant discover data each time the server reconnects.

I will work on a "more formal" proposal regarding the last solution and submit a PR, but I have the feeling that this would imply a lot of code rewriting both on the server and the client.

**Comment by t-mullen** [comment]
`socket.id` is used to identify connections, not peers. The README should be updated to be more accurate here. The demo does indeed use socket ids to identify peers, but only out of simplicity.

Peer identification and authentication in the sense of "one computer" being a peer is the responsibility of the application. You could use client-generated random numbers, SSO tokens, phone numbers, first names, passwords, public keys, whatever. All simple-signal cares about is routing messages, so it only cares about sockets.

As for the server restarting and socket ids changing, this makes sense. Peer ids shouldn't change, but these aren't peer ids, they're route ids. If the server restarts, routes change.

You need to implement some mapping of persistent peer identifiers. This is possible through the metadata objects and forwarding:

```javascript
const MY_PEER_ID = cuid() // or anything, hopefully authenticated
var signalClient = new SimpleSignalClient(socket, MY_PEER_ID)

signalClient.on('ready', (peerIds) => {
  signalClient.connect(peerIds[0]) // we aren't connecting via socket.ids, we're connecting via our "peer id" abstraction, we could use the metadata field instead of using a target
})
```

The server then stores and uses this arbitrary information to figure out a routing id.
```javascript
signalServer.on('discover', function (request) {
  request.discover(ALL_PEER_IDS)
  ALL_PEER_IDS.addRoute(request.metadata, request.initiator.id)
})
signalServer.on('request', function (request) {
  var peerId = ALL_PEER_IDS.getRoute(request.receiver.id) // we could also have used request.metadata instead of the target/receiver
  request.forward(peerId)
})
```

**Comment by t-mullen** [comment]
I'll admit this is a bit confusing, especially since I mashed terminology a bit in the README (should be better now). If you have any ideas for improving this without building peer identification into the module, I'd be happy to hear them.

**Comment by d-asensio** [comment]
It makes a lot of sense 😄

Sure! If I have some ideas about improvements you'll hear from me!

**Comment by d-asensio** [comment]
BTW: Thank you for the time you took to answer this accurately!

**Comment by t-mullen** [comment]
I've given more though to this and changed a few things in the most recent major version, notably the removal of the "routing ID" concept. Everything is done with hidden session-tracking numbers now and `socket.id` is not used anywhere. Identification/authentication is purely custom.

Thanks for your suggestions on this.
