### ISSUE TITLE
Add `deny` option in addition to `accept`

### ISSUE THREAD

**Issue by RangerMauve** [t-mullen/simple-signal#18]
Sometimes an application will reach a limit on the number of peers it wants to be connected to. Would it be possible to add a `request.deny()` API to make it possible to signal to a peer that their request won't be accepted and that they should try someone else?

**Comment by t-mullen** [comment]
Added as `request.reject([metadata])` in `v2.1.0`.

**Comment by RangerMauve** [comment]
Awesome, thank you!
