### ISSUE TITLE
connect() promise does not resolve sometimes

### ISSUE THREAD

**Issue by gurupras** [t-mullen/simple-signal#19]
I'm trying to start implementing something akin to an SFU. In my setup, my nodeJS backend starts a simple-peer instance and announces itself as the only node to each client.

However, when I do this, I see that the client's `connect()` promises never resolve.
I tracked this down to the following line: https://github.com/t-mullen/simple-signal/blob/19f4226ed5d3dffdef99ba2dfc3c503bfe90d700/client/src/index.js#L70

For some reason, the problem seems to be that `metadata` is `null` when I have a `wrtc` peer which in turn never allows connect to resolve.
https://github.com/t-mullen/simple-signal/blob/19f4226ed5d3dffdef99ba2dfc3c503bfe90d700/client/src/index.js#L99-L101

I have also confirmed that the connection itself has been established successfully as I can call `signalClient.peers()[0].send('hello')` and have the nodeJS simple-peer instance receive it. In other words, the problem seems to be that `connect()` _only_ resolves if there is metadata available even though this isn't a hard-requirement for actual connection establishment.

**Comment by t-mullen** [comment]
Are you explicitly passing `null` to the metadata arguments for `accept` or `connect` on either side?

**Comment by gurupras** [comment]
Yup! It looks like that's what's causing this.

However, I still think this is a valid issue. The question being whether the `connect()` promise should resolve only if metadata is available.

Since I don't really know/care about what metadata is supposed to contain, I was passing `null` on _both_ sides.

```
const { peer } = await signalClient.connect(peerID, null, {
  offerOptions: {
    offerToReceiveAudio: true,
    offerToReceiveVideo: true
  },
  answerOptions: {
    offerToReceiveAudio: true,
    offerToReceiveVideo: true
  },
  trickle: false,
  wrtc
})
```

I guess my issue is with the call signature. In cases where metadata is not important, I can call the function with either `undefined` or `{}`, but not `null`; which doesn't feel natural to me.

**Comment by t-mullen** [comment]
You're right, the check on line 70 should be `metadata === undefined` instead of a falsely check.

**Comment by t-mullen** [comment]
Passing `null` as metadata and discoveryData is fine in `v2.1.0`.
