### ISSUE TITLE
Resolve accept/connect promise after connect event

### ISSUE THREAD

**Issue by stevemk14ebr** [t-mullen/simple-signal#20]
When the accept or connect promise is generated it resolves before the connect callback event is raised by simple-peer. This causes peer.send()'s directly after an await accept/connect to fail as there's a race to create the data channel. I propose waiting for the connect before the promise is resolved, so that users do not need to do the following:

```
const { peer } = await request.accept(undefined, {wrtc: wrtc, stream: this.stream});
await new Promise((resolve, reject) => {
    peer.on('connect', () => {
        resolve();
    });
});
peer.send('first message');
```

https://github.com/feross/simple-peer/issues/452

**Comment by t-mullen** [comment]
The `stream` event can fire before the `connect` event. `stream` event listeners attached after `connect` fires might miss streams.

**Comment by t-mullen** [comment]
`peer.write()` can be used before `connect`. `peer.send()` is also unsafe for large messages, so you should prefer `peer.write()` unless you're doing something unusual.

```javascript
const { peer } = await request.accept(undefined, {wrtc, stream: this.stream});
peer.write('first message');
```

**Comment by t-mullen** [comment]
I'm thinking we can solve this by adding some convenience functions for events to the peer object. What do you think of this:
```javascript
const { peer } = await request.accept(undefined, {wrtc, stream: this.stream});
await peer.event('connect');
peer.send('first message');
const data = await peer.event('data');
```

**Comment by stevemk14ebr** [comment]
Honestly i don't know, the api seems confusing on the order of what happens when and when it's safe to use what methods. I would suggest either better documentation or more guarantees on what is available after awaiting on some promises.

**Comment by t-mullen** [comment]
You are right - this is confusing.

I've hopefully solved this in `2.2.0`. You can now either listen to the `connect` event, or ignore it all together. The peer is connected when `accept()` or `connect()` resolve. `stream` and `track` events are safely cached so you won't miss them.

This generally means you don't need to worry about event orders and the semantics still work. All of the following are valid now:

```javascript
await request.accept()
peer.send('data')
```
```javascript
await request.accept()
peer.on('connect', () => {
  peer.send('data')
})
```
```javascript
await request.accept()
peer.send('data')
peer.on('stream', (stream) => {
   // we don't miss stream events, even if they fire BEFORE our promise resolves
})
```

**Comment by t-mullen** [comment]
If you have concerns with any other parts of the API, I'd love to hear them.

**Comment by stevemk14ebr** [comment]
Thanks works great, i think with this change it is simple enough to understand. The metadata and peerOptions objects should be described better in documentation i think though. And a small example may be useful, here's a pretty basic project i did for school, feel free to gut it and use whatever you like if you decide to make an example: https://github.com/stevemk14ebr/VideoCall

**Comment by t-mullen** [comment]
Some reference to simple-peer's documentation should be there for `peerOptions`.

Not much to document for `metadata` - it's really just any object your application wants. It's in the API since almost every WebRTC application uses some kind of extra signal data.

Totally agree about the examples! There should be a bunch!

**Comment by t-mullen** [comment]
Added the first of what should be a couple examples here: https://github.com/t-mullen/simple-signal/tree/2.2.1/examples/lobbys

It's a bit more advanced, showing how `discoveryData` and `metadata` can be used to create additional signalling structure. Let me know if you'd like more of these "real world" examples.
