### ISSUE TITLE
Timeout feature for connect request.

### ISSUE THREAD

**Issue by tinchoz49** [t-mullen/simple-signal#23]
Hi @t-mullen, how are you?

I've been experimenting a random issue where sometimes when a peer runs a `connect`, the promise stay there because the other peer was disconnected later.

Something like this:
![timeout](https://user-images.githubusercontent.com/819446/61822419-df073c00-ae2f-11e9-957e-798169f5a8f0.jpg)

I was thinking that as a solution since this a common request process we can add a timeout option.

What do you think?

For now I override the connect method with this timeout feature: https://github.com/geut/discovery-swarm-webrtc/blob/new-webrtc-swarm/lib/signal-client.js#L59

**Comment by t-mullen** [comment]
Sounds good to me!
