### ISSUE TITLE
Disconnect listeners being removed can cause compatibility issues

### ISSUE THREAD

**Issue by pshah123** [t-mullen/simple-signal#25]
Currently it seems `socket.on('disconnect', ...` listeners are being removed. This causes compatibility issues if the `socket.io` instance is being used by other services that listen to `disconnect`.

**Workaround**: for now, using `socket.on('disconnecting', ...` is a quick fix for most use cases.

I would propose not removing the other listeners and instead issuing a console warning if there are other listeners present.

**Comment by t-mullen** [comment]
Fixed in `simple-signal-server@2.1.1`
