### ISSUE TITLE
[simple-signal-server]: Clearing out this._sockets

### ISSUE THREAD

**Issue by gurupras** [t-mullen/simple-signal#28]
First, sorry if this is a totally dumb question.

I've been running into some memory leaks recently, and an amateur attempt at a heap dump 
![image](https://user-images.githubusercontent.com/2933207/81376102-d89d3480-90d0-11ea-8bfa-0c1f99d3df8a.png)
led me to this line of code. From the code below, I see that `this._sockets` (temporarily?) stores sockets that are amidst discovery.
https://github.com/t-mullen/simple-signal/blob/ec5ff0fe9ee7e7a8bfd650f60bd47fa6e03c5017/server/src/index.js#L21-L24

but I can't seem to figure out where `this._sockets` is cleared out.

Does a socket disconnect somehow wipe it out? Am I somehow not releasing a reference to the sockets in _my_ code that is in turn causing a pileup within `SimpleSignalServer`?

**Comment by t-mullen** [comment]
Yes, this is a leak. Fixed in `v2.1.2`
