### ISSUE TITLE
Why do the server cares about the connected peers?

### ISSUE THREAD

**Issue by d-asensio** [t-mullen/simple-signal#8]
After submitting my pull request #7 I realized that something is conceptually wrong with keeping on the server an array of connected peers:

https://github.com/t-mullen/simple-signal/blob/00a8284f38df7cc390117c355752f5ff22456d13/server/src/simple-signal-server.js#L15

As I see, the problem is that a signaling server does not have to care about "which" or "how many" peers are connected, it should only help peers connect to each other.

Conceptual problems apart, it is technically impossible to keep track of the connected peers since its impossible to detect when they disconnect, and that array will grow and grow wasting more and more memory until the node process dies (memory leak):

https://github.com/t-mullen/simple-signal/blob/00a8284f38df7cc390117c355752f5ff22456d13/server/src/simple-signal-server.js#L62

In addition, as you can see in the previous code snippet, the peers are tightly coupled to the socket ID, so if for some reason you want to know which peers are connected to the signaling server via socket (not between them), you can always ask for `Object.keys(self._sockets)`.

Or I'm wrong and I'm not being able to see what's the real reason for keeping this array 😅

**Comment by d-asensio** [comment]
I have submitted a PR with the changes #9

**Comment by t-mullen** [comment]
Not sure. You're right that it seems to have no purpose. Merged PR 👍
